name: Manual trigger AutoQA Test Runner

on:
  workflow_dispatch:
    inputs:
      jan_app_url_windows:
        description: 'URL to download Jan app for Windows (.exe)'
        required: true
        type: string
        default: 'https://delta.jan.ai/nightly/Jan-nightly_0.6.5-758_x64-setup.exe'
      jan_app_url_ubuntu:
        description: 'URL to download Jan app for Ubuntu (.deb)'
        required: true
        type: string
        default: 'https://delta.jan.ai/nightly/Jan-nightly_0.6.5-758_amd64.deb'
      jan_app_url_macos:
        description: 'URL to download Jan app for macOS (.dmg)'
        required: true
        type: string
        default: 'https://delta.jan.ai/nightly/Jan-nightly_0.6.5-758_universal.dmg'
      is_nightly:
        description: 'Is this a nightly build?'
        required: true
        type: boolean
        default: true

jobs:
  call-autoqa-template:
    uses: ./.github/workflows/autoqa-template.yml
    with:
      jan_app_windows_source: ${{ inputs.jan_app_url_windows }}
      jan_app_ubuntu_source: ${{ inputs.jan_app_url_ubuntu }}
      jan_app_macos_source: ${{ inputs.jan_app_url_macos }}
      is_nightly: ${{ inputs.is_nightly }}
      source_type: 'url'
    secrets:
      RP_TOKEN: ${{ secrets.RP_TOKEN }}
